version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - EMAIL_USER=your-email@gmail.com
      - EMAIL_PASS=your-email-password
    depends_on:
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - app-network

  consumer:
    build: .
    command: node src/rabbitmq/consumer.js   # Correct path for consumer file
    depends_on:
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
